### ISSUE TITLE
Release PDB2PQR 3

### ISSUE THREAD

**Issue by sobolevnrm** [Electrostatics/pdb2pqr#129]
The goal for PDB2PQR 3 is to be a pip-only install.  This means (temporarily) dropping PDB2PKA/APBS support from within PDB2PQR.  Since APBS is in development limbo, integration with PDB2PQR will be difficult anyway and there are some PDB2PQR bug fixes that need to be released sooner rather than later.  @speleo3 and @orbeckst -- does this cause you any concern?

If not, then we need to finish the following things:

- [x] Work with @Eo300 to make both PDB2PQR 2.2.1 and 3 available on web server
- [x] Ask for help from @tsenapathi for conda package
- [x] Release on PyPI
- [x] Update documentation with information about temporary removal of PDB2PKA
- [x] Update documentation with pip-based installation instructions
- [x] Update change log with updates below (after PR #154 is resolved)
- [x] Attempt to address some of #58 and #59 
- [x] Waiting on PR merge -- Finish #102
- [x] Waiting on PR merge -- Resolve #125
- [x] Waiting on PR merge -- Fix #147
- [x] Waiting on PR merge -- Fix #139 
- [x] Waiting on PR merge -- Fix #140 
- [x] Waiting on PR merge -- Fix #109 
- [x] Waiting on PR merge -- Fix #130 (thanks @speleo3 )
- [x] Waiting on PR merge -- Fix #132 
- [x] Waiting on PR merge -- Fix #133 
- [x] Waiting on PR merge -- Fix #138 
- [x] Fix #131 
- [x] Fix https://github.com/jensengroup/propka/issues/93
- [x] Finish #101
- [x] Make sure that pH stability profile is parsed correctly in PDB2PQR (created as #139)

What does everyone think?  @intendo @speleo3 @orbeckst @Eo300 @tsenapathi 

Thanks!

**Comment by orbeckst** [comment]
I don't have a tremendous amount of insights into current pdb2pqr but the general strategy sounds sensible, especially with a view towards maintainability. I would only add that using semantic versioning might help in making clear to users which versions of pdb2pqr have the capabilities that they require.

**Comment by tsenapathi** [comment]
Great idea @sobolevnrm! I will work on the packaging. Please let me know when there is a version that I can work with.

**Comment by speleo3** [comment]
A release without PDB2PKA support works for me. I agree with @orbeckst that semantic versioning would make sense. Are there any backwards incompatible changes compared to the 3.0.1 release on PyPI? https://pypi.org/project/pdb2pqr/#history

**Comment by sobolevnrm** [comment]
Thanks, all!  I was definitely thinking of a 3.1 release.  This shouldn't
cause any backwards compatibility issues with respect to 3.0 besides
changing the installation mechanism.

Thanks again!

**Comment by intendo** [comment]
Have we closed the loop with @Eo300?
Basically, is there anything you need from me at this point to help make release 3.1 possible?

**Comment by sobolevnrm** [comment]
> Have we closed the loop with @Eo300?
> Basically, is there anything you need from me at this point to help make release 3.1 possible?

Could you please follow up with @Eo300 ?  Thanks!

**Comment by sobolevnrm** [comment]
@tsenapathi -- the code is ready for a conda release when you have time:  https://github.com/Electrostatics/pdb2pqr/releases/tag/v3.1.0

Thank you!

**Comment by tsenapathi** [comment]
> @tsenapathi -- the code is ready for a conda release when you have time: https://github.com/Electrostatics/pdb2pqr/releases/tag/v3.1.0
> 
> Thank you!

Great! Thanks @sobolevnrm I will work on this

**Comment by tsenapathi** [comment]
@sobolevnrm I am ready with the conda package. Can you have a look at the propka update ([](https://github.com/conda-forge/propka-feedstock/pull/8)) and merge if all good. I would like to use the latest version for this package.

**Comment by Eo300** [comment]
> Work with @Eo300 to make both PDB2PQR 2.2.1 and 3 available on web server

Would this feature manifest as a dropdown on the configuration page, adjusting the options on the page accordingly?

**Comment by sobolevnrm** [comment]
> > Work with @Eo300 to make both PDB2PQR 2.2.1 and 3 available on web server
> 
> Would this feature manifest as a dropdown on the configuration page, adjusting the options on the page accordingly?

That would be great!

**Comment by Eo300** [comment]
Sounds good, I'll get started with that

**Comment by tsenapathi** [comment]
> > @tsenapathi -- the code is ready for a conda release when you have time: https://github.com/Electrostatics/pdb2pqr/releases/tag/v3.1.0
> > Thank you!
> 
> Great! Thanks @sobolevnrm I will work on this

Conda package is up in conda-forge now (https://anaconda.org/conda-forge/pdb2pqr)

**Comment by speleo3** [comment]
@tsenapathi may I suggest some changes to the conda recipe?

- remove `pytest` from run requirements
- add `requests` to run requirements (and remove it from test requirements)

If you like I can send a pull request.

**Comment by tsenapathi** [comment]
> @tsenapathi may I suggest some changes to the conda recipe?
> 
> * remove `pytest` from run requirements
> * add `requests` to run requirements (and remove it from test requirements)
> 
> If you like I can send a pull request.

Of Course, send the pull request

**Comment by speleo3** [comment]
https://github.com/conda-forge/pdb2pqr-feedstock/pull/1
